source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

platform :ios, '8.0'

target 'GDProtocolMediator_Example' do
  pod 'GDProtocolMediator', :path => '../'

  target 'GDProtocolMediator_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
