# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :code_coverage do |options|
    slather(
  		input_format: "auto",
  		scheme: options[:scheme],
  		workspace: options[:workspace],
  		proj: options[:proj],
  		html: true,
  		# simple_output: true, # 打开会导致无法生成html 尴_尬
  		# show: true,
  		ignore: ["../*", "Example/*", "*.h"],
  		output_directory: options[:output_directory],
  		build_directory: options[:build_directory],
	)
  end
end
